require("core")

require("config.autostart")
require("config.env")
require("config.apps")
require("config.monitors")
require("config.bindings")
require("config.looknfeel")
require("config.layouts")
require("config.misc")
require("config.input")
